// This code was generated by the tool, do not modify it manually
// https://pub.dev/packages/peg

import 'dart:async';
import 'dart:convert';

import 'test2_parser.dart';

export 'test2_parser.dart';

/// The [Test2Converter] converts data to [Object?] value.
///
/// If event-based parsing is required, then the corresponding parser instance
/// (with event handlers) must be passed as a constructor argument.
class Test2Converter with Converter<String, Object?> {
  final Test2Parser _parser;

  Test2Converter({
    Test2Parser? parser,
  }) : _parser = parser ?? Test2Parser();

  @override
  Object? convert(String input) {
    final result = parseString(_parser.parseStart, input);
    return result;
  }

  @override
  Sink<String> startChunkedConversion(Sink<Object?> sink) {
    final input = parseAsync(_parser.parseStart$Async, (result) {
      try {
        final value = result.getResult();
        sink.add(value);
      } catch (error, stackTrace) {
        if (sink case final EventSink<Object?> sink) {
          sink.addError(error, stackTrace);
        } else {
          rethrow;
        }
      }
    });

    return input;
  }
}
