%%

bool flag = false;

%%

Start =
     (v:SkipUntil SkipUntil)
  / (v:SkipTil SkipTil)
  / (v:TakeUntil TakeUntil)
  / (v:TakeTil TakeTil)
  / (v:AndPredicateAction AndPredicateAction)
  / (v:OrderedChoiceWithLiterals OrderedChoiceWithLiterals)
  ;

AndPredicateAction = &{ flag ? true : state.fail(const ErrorMessage(0, 'error')) }  v:Integer ;

int
Integer = v:$[0-9]+ <int>{ $$ = int.parse(v); } ;

OrderedChoiceWithLiterals =
    'abc'
  / 'ab'
  / 'a'
  / 'def'
  / 'de'
  / 'd'
  / 'gh'
  ;

SkipUntil =  (!'END'  v:.)* ;

SkipTil =  (![E]  v:.)* ;

TakeTil =  $(![E]  v:.)* ;

TakeUntil =  $(!'END'  v:.)* ;