%%

bool flag = false;

String text = '';

%%

Start =
    (v:AndPredicate AndPredicate)
  / (v:AnyCharacter AnyCharacter)
  / (v:CharacterClass CharacterClass)
  / (v:CharacterClassChar32 CharacterClassChar32)
  / (v:CharacterClassCharNegate CharacterClassCharNegate)
  / (v:CharacterClassCharNegate32 CharacterClassCharNegate32)
  / (v:CharacterClassRange32 CharacterClassRange32)
  / (v:Cut Cut)
  / (v:Cut1 Cut1)
  / (v:CutWithInner CutWithInner)
  / (v:Eof Eof)
  / (v:Expected Expected)
  / (v:Indicate Indicate)
  / (v:Literal0 Literal0)
  / (v:Literal1 Literal1)
  / (v:Literal2 Literal2)
  / (v:Literal10 Literal10)
  / (v:Literals Literals)
  / (v:List List)
  / (v:List1 List1)
  / (v:MatchString MatchString)
  / (v:Message Message)
  / (v:NotPredicate NotPredicate)
  / (v:NotPredicate2 NotPredicate2)
  / (v:OneOrMore OneOrMore)
  / (v:OneOrMoreLiteral OneOrMoreLiteral)
  / (v:OrderedChoice2 OrderedChoice2)
  / (v:OrderedChoice3 OrderedChoice3)
  / (v:Optional Optional)
  / (v:RepetitionMax RepetitionMax)
  / (v:RepetitionMin RepetitionMin)
  / (v:RepetitionMinMax RepetitionMinMax)
  / (v:RepetitionN RepetitionN)
  / (v:Sequence1 Sequence1)
  / (v:Sequence1WithAction Sequence1WithAction)
  / (v:Sequence1WithVariable Sequence1WithVariable)
  / (v:Sequence1WithVariable Sequence1WithVariable)
  / (v:Sequence1WithVariableWithAction Sequence1WithVariableWithAction)
  / (v:Sequence2 Sequence2)
  / (v:Sequence2WithAction Sequence2WithAction)
  / (v:Sequence2WithVariable Sequence2WithVariable)
  / (v:Sequence2WithVariables Sequence2WithVariables)
  / (v:Sequence2WithVariableWithAction Sequence2WithVariableWithAction)
  / (v:Sequence2WithVariablesWithAction Sequence2WithVariablesWithAction)
  / (v:Slice Slice)
  / (v:StringChars StringChars)
  / (v:Tag Tag)
  / (v:Verify Verify)
  / (v:ZeroOrMore ZeroOrMore)
  ;

AndPredicate = &([0] [1] [2]) [0] [1] [2] ;

AnyCharacter = . ;

CharacterClass = [0-9] ;

CharacterClassChar32 = [🚀] ;

CharacterClassCharNegate = [^0] ;

CharacterClassCharNegate32 = [^🚀] ;

CharacterClassRange32 = [ -🚀] ;

Cut =
    [0] [+] ↑ [1]
  / [0]
  ;

Cut1 =
    [0] ↑
  / [1]
  ;

CutWithInner =
    [0] ↑ ([a] / [b]) [1]
  / [0]
  ;

Eof = [0] @eof() ;

Expected = @expected('digits', [0-9]{2,}) ;

Indicate = @indicate('error', [0][1][2]) ;

List = @list([0], [,] v:[0]) ;

List1 = @list1([0], [,] v:[0]) ;

Literal0 = '' ;

Literal1 = '0' ;

Literal2 = '01' ;

Literal10 = '0123456789' ;

Literals = '0123' / '012' / '01' / 'ab' / 'a' / 'A' ;

MatchString = @matchString({ text }) ;

Message = @message('error', [0][1][2]) ;

NotPredicate = !([0] [1] [2]) [0] [1] ;

NotPredicate2 =
     !([0] [3] 'abc' 'foo') [0] [3] 'abc'
   / [0] [3] [2]
  ;

OneOrMore = [0]+ ;

OneOrMoreLiteral = 'abc'+ ;

OrderedChoice2 = [0] / [1] ;

OrderedChoice3 = [0] / [1] / [2] ;

Optional = [0]? [1] ;

RepetitionMax = [🚀]{,3} ;

RepetitionMin = [🚀]{3,} ;

RepetitionMinMax = [🚀]{2,3} ;

RepetitionN = [🚀]{3} ;

Sequence1 = [0] ;

Sequence1WithAction = [0] <int>{ $$ = 0x30; } ;

Sequence1WithVariable = v:[0] ;

Sequence1WithVariableWithAction = v:[0] <int>{ $$ = v; } ;

Sequence2 = [0] [1] ;

Sequence2WithAction = [0] [1] <int>{ $$ = 0x30; } ;

Sequence2WithVariable = v:[0] [1] ;

Sequence2WithVariables = v1:[0] v2:[1] ;

Sequence2WithVariableWithAction = v:[0] [1] <int>{ $$ = v; } ;

Sequence2WithVariablesWithAction = v1:[0] v2:[1] <int>{ $$ = v1 + v2; } ;

Slice = $([0] [1] [2]) / $([0] [1]) ;

StringChars = @stringChars($[0-9]+, [\\], [t] <String>{ $$ = '\t'; }) ;

Tag = @tag('FOR', $([Ff] [Oo] [Rr])) ;

Verify =
    'abc'
  / [5] [6] [7]
  / Verify_
  ;

@inline
Verify_ = @verify('error', [0-1], { $$ == 0x30 }) ;

ZeroOrMore = [0]* ;