%%

bool flag = false;

String text = '';

%%

Start =
    (v:SkipUntil SkipUntil)
  / (v:SkipTil SkipTil)
  / (v:TakeUntil TakeUntil)
  / (v:TakeTil TakeTil)
  / (v:OrderedChoiceWithLiterals OrderedChoiceWithLiterals)
  / (v:OrderedChoiceWithLiterals OrderedChoiceWithLiterals)
  ;

OrderedChoiceWithLiterals =
    'abc'
  / 'ab'
  / 'a'
  / 'def'
  / 'de'
  / 'd'
  / 'gh'
  ;

SkipUntil =  (!'END' v:.)* ;

SkipTil =  (![E] v:.)* ;

TakeTil =  $(![E] v:.)* ;

TakeUntil =  $(!'END' v:.)* ;
