%%

bool flag = false;

String text = '';

%%

Start =
    (v:MatchString MatchString)
  / (v:SkipUntil SkipUntil)
  / (v:SkipTil SkipTil)
  / (v:TakeUntil TakeUntil)
  / (v:TakeTil TakeTil)
  / (v:OrderedChoiceWithLiterals OrderedChoiceWithLiterals)
  / (v:OrderedChoiceWithLiterals OrderedChoiceWithLiterals)
  / (v:Verify41 Verify41)
  / (v:VerifyFlag VerifyFlag)
  ;

int
Integer = v:$[0-9]+ <int>{ $$ = int.parse(v); } ;

MatchString = @matchString({ text });

OrderedChoiceWithLiterals =
    'abc'
  / 'ab'
  / 'a'
  / 'def'
  / 'de'
  / 'd'
  / 'gh'
  ;

SkipUntil =  (!'END'  v:.)* ;

SkipTil =  (![E]  v:.)* ;

TakeTil =  $(![E]  v:.)* ;

TakeUntil =  $(!'END'  v:.)* ;

Verify41 = @verify(Integer, {
    if ($$ != 41) { state.failAt(state.failPos, ErrorMessage(pos - state.failPos, 'error')); }
  }) ;

VerifyFlag = @verify('', {
    if (!flag) { state.failAt(state.failPos, ErrorMessage(pos - state.failPos, 'error')); }
  }) ;