%{
//ignore_for_file: prefer_conditional_assignment, prefer_final_locals

}%

`Object?`
A =>
  $ = (
    $ = '' AndAbc [0]
    ----
    $ = AnyChar AnyCharVoid [0]
    ----
    $ = Char16 Char16Void [0]
    ----
    $ = Chars16 Chars16Void [0]
    ----
    $ = Char32 Char32Void [0]
    ----
    $ = Chars32 Chars32Void [0]
    ----
    $ = Literal0 Literal0Void [0]
    ----
    $ = Literal1 Literal1Void [0]
    ----
    $ = Literal2 Literal2Void [0]
    ----
    $ = Match MatchVoid [0]
    ----
    $ = NotDigits NotDigitsVoid [0]
    ----
    $ = '' NotAbc [0]
    ----
    $ = OneOrMore OneOrMoreVoid [0]
    ----
    $ = Optional OptionalVoid [0]
    ----
    $ = OrderedChoice OrderedChoiceVoid [0]
    ----
    $ = Ranges RangesVoid [0]
    #----
    #$ = Seq2 Seq2Void [0]
    #----
    #$ = Seq3 Seq3Void [0]
    ----
    $ = TakeWhile TakeWhileVoid [0]
    ----
    $ = TakeWhile1 TakeWhile1Void [0]
    ----
#   $ = Verify [0]
#   ----
    $ = ZeroOrMore ZeroOrMoreVoid [0]
    )

AndAbc => &'abc'

AnyChar => $ = .

AnyCharVoid => $ = .

Char16 => $ = [a]

Char16Void => [a]

Chars16 => $ = [a-zA-Z]

Chars16Void => [a-zA-Z]

Char32 => $ = [\u{1f800}]

Char32Void => $ = [\u{1f800}]

Chars32 => $ = [\u{1f800}-\u{1f803}]

Chars32Void =>[\u{1f800}-\u{1f803}]

Literal0 => $ = ''

Literal0Void => ''

Literal1 => $ = 'a'

Literal1Void => 'a'

Literal2 => $ = 'ab'

Literal2Void => 'ab'

Match => $ = <[a]+>

MatchVoid => <[a]+>

NotAbc => !'abc'

NotDigits => $ = [^0-9]

NotDigitsVoid => [^0-9]

OneOrMore => $ = 'abc'+

OneOrMoreVoid => 'abc'+

Optional => $ = 'abc'?

OptionalVoid => 'abc'?

OrderedChoice =>  $ = ($ = 'a' / $ = 'b' / $ = 'c')

OrderedChoiceVoid =>  ($ = 'a' / $ = 'b' / $ = 'c')

Ranges => $ = < [{30-39}{41-5A}{61-7A}] >

RangesVoid => < [{30-39}{41-5A}{61-7A}] >

#Seq2 => a:'a' b:'b' $ = `String` { $$ = a + b; }

#`void`
#Seq2Void => 'a' 'b'

#Seq3 => a:'a' b:'b' c:'c' $ = `String` { $$ = a + b + c; }

#`void`
#Seq3Void => 'a' 'b' 'c'

TakeWhile => $ = <[a]*>

TakeWhileVoid => <[a]*>

TakeWhile1 => $ = <[a]+>

TakeWhile1Void => <[a]+>

#Verify => &{ true }

ZeroOrMore => $ = 'abc'*

ZeroOrMoreVoid => 'abc'*
