// This code was generated by the tool, do not modify it manually
// https://pub.dev/packages/peg
import 'dart:convert';
import 'test_parser.dart';
export 'test_parser.dart';

/// The [TestConverter] converts data to [Object?] value.
///
/// If event-based parsing is required, then the corresponding parser instance
/// (with event handlers) must be passed as a constructor argument.
class TestConverter with Converter<String, Object?> {
  final TestParser _parser;
  TestConverter({
    TestParser? parser,
  }) : _parser = parser ?? TestParser();
  @override
  Object? convert(String input) {
    final result = parseString(_parser.parseStart, input);
    return result;
  }
}
