// This code was generated by the tool, do not modify it manually
// https://pub.dev/packages/peg

import 'dart:convert';

import 'calc_parser.dart';

export 'calc_parser.dart';

/// The [CalcConverter] converts data to [num] value.
///
/// If event-based parsing is required, then the corresponding parser instance
/// (with event handlers) must be passed as a constructor argument.
class CalcConverter with Converter<String, num> {
  final CalcParser _parser;

  CalcConverter({
    CalcParser? parser,
  }) : _parser = parser ?? CalcParser();

  @override
  num convert(String input) {
    final result = parseString(_parser.parseStart, input);
    return result;
  }
}
