// This code was generated by the tool, do not modify it manually
// https://pub.dev/packages/peg
import 'dart:convert';
import 'binary_parser.dart';
export 'binary_parser.dart';

/// The [BinaryConverter] converts data to [AstNode] value.
///
/// If event-based parsing is required, then the corresponding parser instance
/// (with event handlers) must be passed as a constructor argument.
class BinaryConverter with Converter<String, AstNode> {
  final BinaryParser _parser;
  BinaryConverter({
    BinaryParser? parser,
  }) : _parser = parser ?? BinaryParser();
  @override
  AstNode convert(String input) {
    final result = parseString(_parser.parseStart, input);
    return result;
  }
}
